name: Merge staging into main
on:
  workflow_call:
    inputs:
      reviewers:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  merge:
    name: Merge
    runs-on: ubuntu-latest
    steps:

      - name: Open pull request and merge
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        run: |
          {
            # TRY TO CREATE PR
            MERGE_URL=$(gh pr create --base main --head staging \
                        --title "AUTOMERGE - staging -> main" \
                        --body "Merges stating into main for scheduled release" \
                        --reviewer ${{ inputs.reviewers }})
          } || {
            # HANDLE EXCEPTION
            echo "Could not create PR"
            exit 0
          }

          gh pr merge $MERGE_URL -m --admin